project:
  type: book
  output-dir: _book
  resources:
    - "*.qmd"      # Bundles all individual notebooks
    - "data/*"     # Include any raw data folders

book:
  title: "SC3 ABRF R Workshop"
  author: "Devon J. Boland & Christopher Bottoms"
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - R-Introductions.qmd
    - R-coding.qmd
    - R-ilab.qmd
    - R-instrument.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true